<?php
	
	Mage::getSingleton('core/session', array('name' => 'frontend'));
	$_productCollection = Mage::getResourceModel('catalogsearch/advanced_collection')
	->addAttributeToSelect(Mage::getSingleton('catalog/config')->getProductAttributes())
	->addMinimalPrice()
	->addStoreFilter();

	Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($_productCollection);
	Mage::getSingleton('catalog/product_visibility')->addVisibleInSearchFilterToCollection($_productCollection);

	$todayDate = date('m/d/y');
	$tomorrow = mktime(0, 0, 0, date('m'), date('d'), date('y'));
	$tomorrowDate = date('m/d/y', $tomorrow);

	$_productCollection->addAttributeToFilter('special_from_date', array('date' => true, 'to' => $todayDate))
	->addAttributeToFilter('special_to_date', array('or'=> array(
	0 => array('date' => true, 'from' => $tomorrowDate),
	1 => array('is' => new Zend_Db_Expr('null')))
	), 'left');

    $_helper = $this->helper('catalog/output');
    $count = $_productCollection->getSize();
?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">    

    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image 
            if ($_product->getTypeId() == "customproduct" && $_product->getPreviewImage())
            {
                $imagePath = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ) ."image.php?parameters=@width=300@height=290@quality=90@image=/media/catalog/product/previewImage/".$_product->getPreviewImage(); 
                $imgTag = '<img class="previewImage" src="'.$imagePath.' alt="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true).'" />'; 
            }
            else
            {
                $imgTag = '<img src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(300,400).'"  alt="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true).'" />';
            }
            ?>
            
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php echo $imgTag ?></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php //echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <div class="desc std">
                        <?php $short_description = $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <?php echo Mage::helper('core/string')->truncate($short_description, '450'); ?>

                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <?php if($_product->isSaleable()): ?>
                        <p class="product-list-button"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="product-list-button availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" rel="tooltip" title="<?php echo $this->__('Add to Wishlist') ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare" rel="tooltip" title="<?php echo $this->__('Add to Compare') ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
                 
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>
    <?php
        $_span = 'span4';
        $_grid_pro = Mage::getStoreConfig('themeoptions/themeoptions_config/grid_product');
        if ( !$_grid_pro ) { $_grid_pro = 3; }
        switch ($_grid_pro)
        {
        case 2:
            $_span = 'span6';
            break;
        case 3:
            $_span = 'span4';
            break;
        case 4:
            $_span = 'span3';
            break;
        }
    ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $_grid_pro; //$this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <div class="products-grid row-fluid">
        <?php endif ?>
            <div class="<?php echo $_span ?> item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <div class="item-inner">
            <?php
            if ($_product->getTypeId() == "customproduct" && $_product->getPreviewImage() )
            {
                $imagePath = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ) ."image.php?parameters=@width=300@height=290@quality=90@image=/media/catalog/product/previewImage/".$_product->getPreviewImage(); 
                $imgTag = '<img class="previewImage" src="'.$imagePath.'" alt="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true).'" />'; 
            }
            else
            {
                $imgTag = '<img src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(300,400).'"  alt="'.$this->stripTags($this->getImageLabel($_product, 'small_image'), null, true).'" />';
            }
            ?>                    
                    
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><?php echo $imgTag ?></a>
                    <div class="product-details">      
                            <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            <?php if($_product->getRatingSummary()): ?>
                            <?php //echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                            <?php endif; ?>
                            <?php echo $this->getPriceHtml($_product, true) ?>
                            <?php if(!$_product->isSaleable()): ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <div class="actions">
                                <?php if($_product->isSaleable()): ?>
                                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                    
                                <?php endif; ?>
                                
                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to Wishlist') ?>" rel="tooltip"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to Compare') ?>" rel="tooltip"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                                
                            </div>
                    </div>
								<?php
									$newFromDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsFromDate();
									$newToDate = Mage::getModel('catalog/product')->load($_product->getID())->getNewsToDate();                 
									$now = date("Y-m-d H:m:s");
																				   
									if($newFromDate <= $now && $newToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/new_label')) {
								?>
										<div class="label-pro-new"><?php echo $this->__('New'); ?></div>
								<?php }	?>
								
								<?php 
									// Get the Special Price
									$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
									// Get the Special Price FROM date
									$specialPriceFromDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialFromDate();
									// Get the Special Price TO date
									$specialPriceToDate = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialToDate();
									// Get Current date
								 
									if ($specialprice){
										if($specialPriceFromDate <= $now && $specialPriceToDate >= $now && Mage::getStoreConfig('themeoptions/themeoptions_config/sale_label')) {
								?>
												<div class="label-pro-sale"><?php echo $this->__('Sale'); ?></div>
								<?php
									} }
								?>   
                </div>
            </div>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </div>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>
