<?php 
    $barcode = Mage::helper('giftvoucher')->getGeneralConfig('barcode_enable');
    $barcode_type = Mage::helper('giftvoucher')->getGeneralConfig('barcode_type');
    $url_barcode = '';
    if($barcode){
        if($barcode_type == 'code128') $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/default.png';
        else $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/qr.png';
    }
    if(Mage::getStoreConfig('giftvoucher/print_voucher/logo')) $logo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/logo/'.Mage::getStoreConfig('giftvoucher/print_voucher/logo');
    else $logo = $this->getSkinUrl('images/logo_print.gif');
?>
<div id="giftcard-template-left" style="background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/background/left/default.png' ?>);" >
    <div class="giftcard-template-content-left giftcard-change-image" >
        <a href="#" style="float:left;text-align:center;position:relative; max-width: 100%;">
        <img id="img-type-left" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/left/default.png' ?>"/>
       
       
        <div class = "giftcard-logo">
         <img src="<?php echo $logo; ?>"/>
            <!--div class="logo1" style="background: url(<?php echo $logo; ?>) center no-repeat;"></div-->
        </div>
         </a>
    </div>
    <style>
       #giftcard-template-left .giftcard-change-image, #giftcard-template-left .giftcard-template-content{
            background: none !important;
       }       
    </style>
    <div class="giftcard-template-content" style="background:none transparent; " >
        <div class="giftcard-style-color giftcard-title">
            <?php echo $this->__('Giftcard Title') ?>
        </div>
        <div class="giftcard-from-to">
            <span class="giftcard-from">
                <label class="giftcard-text-color" for="giftcard-from"><?php echo $this->__('from') ?>:</label>
                <span class="giftcard-style-color giftcard-send-from">&nbsp;<?php echo Mage::helper('customer')->isLoggedIn() ? Mage::helper('customer')->getCustomerName() : ''; ?></span>
            </span>
            <span class="giftcard-to">
                <label class="giftcard-text-color" for="giftcard-to"><?php echo $this->__('to') ?>: </label>
                <span class="giftcard-style-color giftcard-send-to">&nbsp;</span>
            </span>
        </div>
        <div class ="giftcard-box">
            <div class ="giftcard-text-box")>
                    <pre class="giftcard-text-color giftcard-custom-message"></pre>
            </div>
        </div>
        <div class="giftcard_value">
            <span class="giftcard-text-color" ><?php echo $this->__('Value') ?></span>            
            <span class="giftcard-style-color giftcard-price-change">$100.00</span>
        </div>
        <div class="giftcard-code">            
            <span class = "giftcard-number">
                <label class="giftcard-text-color"><?php echo $this->__('Gift Card Number') ?>:</label>
                <?php if($url_barcode != ''): ?>
                <span class="giftcard-style-color">GIFT-XXXX-XXXX</span>
                <?php endif; ?>
            </span>
            <span class = "giftcard-barcode">
                <?php if($url_barcode != ''): ?>
                <img src="<?php echo $url_barcode ?>"/>
                <?php else: ?>
                <span class="giftcard-style-color">GIFT-XXXX-XXXX</span>
                <?php endif; ?>
            </span>
        </div>
        <div class="giftcard-text">
            <p class="giftcard-text-color"><?php echo Mage::getSingleton('giftvoucher/giftvoucher')->getPrintNotes(); ?></p>
        </div>
    </div>
</div>
