<?php 
    $barcode = Mage::helper('giftvoucher')->getGeneralConfig('barcode_enable');
    $barcode_type = Mage::helper('giftvoucher')->getGeneralConfig('barcode_type');
    $url_barcode = '';
    if($barcode){
        if($barcode_type == 'code128') $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/default.png';
        else $url_barcode = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/barcode/qr.png';
    }
    if(Mage::getStoreConfig('giftvoucher/print_voucher/logo')) $logo = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/pdf/logo/'.Mage::getStoreConfig('giftvoucher/print_voucher/logo');
    else $logo = $this->getSkinUrl('images/logo_print.gif');
?>
<div id="giftcard-template-back" style="/*display:none*/">
    <div class="giftcard-template-content" style= "display:none"></div>
    <div class="giftcard-change-image-background-popup giftcard-change-image" style="background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'giftvoucher/template/images/default.png' ?>);  background-repeat: no-repeat;background-size: 655px 400px">
        <div class = "logo-title">
            <div class = "giftcard-logo" style="background:url(<?php echo $logo; ?>) center  no-repeat;"></div>
            <div class="giftcard-style-color giftcard-title"><?php echo $this->__('Giftcard Title') ?></div>
        </div>
        <div class = "from-to">
            <div class = "giftcard-form">
                <label class="giftcard-text-color" for="giftcard-from"><?php echo $this->__('from') ?>:</label>
                <span class="giftcard-style-color giftcard-send-from" id='giftcard-from' >&nbsp;<?php echo Mage::helper('customer')->isLoggedIn() ? Mage::helper('customer')->getCustomerName() : ''; ?></span>
            </div>
            <div class = "giftcard-to" style="">
                <label class="giftcard-text-color" for="giftcard-to"><?php echo $this->__('to') ?>: </label>
                <span class="giftcard-style-color giftcard-send-to" id='giftcard-to'>&nbsp;</span>
            </div>
        </div>
        <div class = "giftcard-box">
            <div class = "giftcard-text-box"><pre class="giftcard-text-color giftcard-custom-message"></pre></div>
        </div>
        <div class = "giftcard-value-barcode">
            <div class = "giftcard_value">
                <div class="giftcard-text-color"><?php echo $this->__('Value') ?></div>
                <div class="giftcard-style-color giftcard-price-change">$100.00</div>
            </div>
            <div class ="giftcard-barcode">    
                <?php if($url_barcode != ''): ?>
                <div class="giftcard-number">
                    <label class="giftcard-text-color"><?php echo $this->__('Gift Card Number') ?>:</label>
                    <span class="giftcard-style-color" style="">GIFT-XXXX-XXXX</span>
                </div>
                <span class = "barcode"><img src="<?php echo $url_barcode ?>" /></span>
                <?php else: ?>
                <div class="giftcard-text-color"><?php echo $this->__('Gift Card Number') ?></div>
                <div class="giftcard-style-color">GIFT-XXXX-XXXX</div>
                <?php endif; ?>
            </div>
        </div>
        <div class = "giftcard-note">
            <div class = "form-note">
                <p class="giftcard-text-color"><?php echo Mage::getSingleton('giftvoucher/giftvoucher')->getPrintNotes(); ?></p>
            </div>
        </div>

    </div>
</div>