<!--
/**
 * Klarna
 * JavaScript includes for OnePageCheckout
 */
-->
<?php $kittPath = Klarna_KlarnaPaymentModule_Helper_Checkout::STATIC_KITT; ?>
<link type="text/css" rel="stylesheet" href="<?php echo $kittPath; ?>res/v1.1/checkout.css" />
<script src="<?php echo $kittPath; ?>core/v1.0/js/klarna.min.js" type="text/javascript"></script>
<script src="<?php echo $kittPath; ?>toc/v1.1/js/klarna.terms.min.js" type="text/javascript" charset="utf-8"></script>
<script src="<?php echo $kittPath; ?>letop/v1.0/js/klarna.letop.js" type="text/javascript" charset="utf-8"></script>
<script src="<?php echo $kittPath; ?>res/v1.1/js/klarna.lib.js" type="text/javascript"></script>
<script src="<?php echo $kittPath; ?>res/v1.1/js/checkout.js" type="text/javascript"></script>
