<?php $_code=$this->getMethodCode() ?>

        <label for="<?php echo $_code ?>_birth" class="required"><em>*</em><?php echo $this->__('Birth date') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_ss_number" name="payment[<?php echo $_code ?>_birth_number]" title="<?php echo $this->__('Birth date') ?>" class="input-text" value="" />
        </div>

        <label for="<?php echo $_code ?>_housenumber" class="required"><em>*</em><?php echo $this->__('House number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_ss_number" name="payment[<?php echo $_code ?>_housenumber]" title="<?php echo $this->__('House number') ?>" class="input-text" value="" />
        </div>