<?php $_code=$this->getMethodCode() ?>
        <label for="<?php echo $_code ?>_ssno" class="required"><em>*</em><?php echo $this->__('Social security number') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_ss_number" name="payment[<?php echo $_code ?>_ss_number]" maxlength="11" title="<?php echo $this->__('Social security number') ?>" class="input-text" value="" />
        </div>
				<input type="hidden" name="pbb-wash-ssno" value="<?php echo $_code ?>_ss_number">