<?php if(count($this->getStores())>1): ?>
<div class="language-switcher" id="easyflags">
    <?php foreach ($this->getStores() as $_lang): ?>
        <a href="<?php echo $_lang->getCurrentUrl() ?>"><img src="<?php echo $this->getSkinUrl('images/flags/' . $this->htmlEscape($_lang->getCode()) . '.gif') ?>" alt="<?php echo $this->htmlEscape($_lang->getName()) ?>"/></a>
    <?php endforeach; ?>
</div>
<?php endif; ?> 