this is test<?php
    $_zoom_w = Mage::getStoreConfig('prozoom/prozoom_config/zoom_w');
    $_zoom_h = Mage::getStoreConfig('prozoom/prozoom_config/zoom_h');
	$_border_w = Mage::getStoreConfig('prozoom/prozoom_config/zoom_border_w');
	$_border_color = Mage::getStoreConfig('prozoom/prozoom_config/zoom_border_color');
    $_lightbox_w = Mage::getStoreConfig('prozoom/prozoom_config/lightbox_w');   
    $_lightbox_h = Mage::getStoreConfig('prozoom/prozoom_config/lightbox_h');
    $_thumbnail_qty = Mage::getStoreConfig('prozoom/prozoom_config/thumbnail_qty');   
    $_thumbnail_w = Mage::getStoreConfig('prozoom/prozoom_config/thumbnail_w');
    $_thumbnail_h = Mage::getStoreConfig('prozoom/prozoom_config/thumbnail_h');
	$_scroll_qty = Mage::getStoreConfig('prozoom/prozoom_config/scroll_qty');
	$_auto = Mage::getStoreConfig('prozoom/prozoom_config/auto_scroll');
	$_zoom_type = Mage::getStoreConfig('prozoom/prozoom_config/zoom_type');
?>
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $ratio = $this->helper('catalog/image')->init($_product, 'image')->getOriginalWidth() / $this->helper('catalog/image')->init($_product, 'image')->getOriginalHeight();
    $newH = 1000 / $ratio;
    $lightbox_h = $lightbox_w / $ratio ;
?>
<div class="row-fluid">
<div class="span2 visible-desktop">
<?php if ( count($this->getGalleryImages()) > 0 ): ?>
	<?php if( (!Mage::getStoreConfig('prozoom/prozoom_config/enabled_thumbnail')) || ( count($this->getGalleryImages()) < $_thumbnail_qty )|| ( count($this->getGalleryImages()) == $_thumbnail_qty )) { ?>
		<div class="more-views more-img">
			<h2><?php echo $this->__('More Views') ?></h2>
			<ul>
			<?php foreach ($this->getGalleryImages() as $_image): ?>
				<li>
					<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(1000,1330); ?>" class="cloud-zoom-gallery" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" name="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>"
										rel="useZoom: 'zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(500,670); ?>'">
					<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbnail_w, $_thumbnail_h); ?>" width="<?php echo $_thumbnail_w ?>" height="<?php echo $_thumbnail_h ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
				</li>
			<?php endforeach; ?>
			</ul>
			<!-- thumbnail for lighbox-->
				<ul class="mt-thumb-light" style="display:none;">
					<?php foreach ($this->getGalleryImages() as $_image): ?>
						<li>
							<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>" rel="lightbox[rotation]" title="<?php echo $_product->getName();?>"></a>
						</li>
					<?php endforeach; ?>                                                                
				</ul>
			<!--##########-->
			<script type="text/javascript">
				//<![CDATA[
					$jq(document).ready(function(){
						$jq('head').append('<style type="text/css"> .cloud-zoom-big { border:<?php echo $_border_w ?>px solid <?php echo $_border_color ?> }</style>');
					});
				//]]>
			</script>
		</div>
	<?php } else { ?>
		
		<div class="more-views more-img thumbnail-vert visible-desktop">
				<h2><?php echo $this->__('More Views') ?></h2>
				<div class="thumb-vert">
					<ul id="thumb-vert-slider" class="jcarousel jcarousel-skin-tango thumb-vertscroller">
					<?php foreach ($this->getGalleryImages() as $_image): ?>
						<li>
							<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(1000,1330); ?>" class="cloud-zoom-gallery" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>"
												rel="useZoom: 'zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(500,670); ?>'">
							<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbnail_w, $_thumbnail_h); ?>"  alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
						</li>
					<?php endforeach; ?>
					</ul>
				</div>
				<?php //thumbnail for lighbox ?>
					<ul class="mt-thumb-light" style="display:none;">
						<?php foreach ($this->getGalleryImages() as $_image): ?>
							<li>
								<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>" rel="lightbox[rotation]" title="<?php echo $_product->getName();?>"></a>
							</li>
						<?php endforeach; ?>                                                                
					</ul>
				<?php //--##########-- ?>
				<script type="text/javascript">
					//<![CDATA[
						$jq(document).ready(function(){
							$jq('#thumb-vert-slider').jcarousel({
								<?php if( $_auto ) { ?>
								auto: 1,
								<?php } else { ?>
								auto: 0,
								<?php } ?>
								vertical: true,
								wrap: 'circular',
								itemWidth: <?php echo $_thumbnail_w ?>,
								visible: 5,
								scroll: 1
							});
							$jq('head').append('<style type="text/css"> .cloud-zoom-big { border:<?php echo $_border_w ?>px solid <?php echo $_border_color ?> }</style>');
						});
					//]]>
				</script>
			</div>
		
	<?php } ?>

<?php endif; ?>
</div>
<div class="span10">
<p class="product-image">
    <?php
        $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(500,670).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
    ?>
	<!-- images for lightbox -->
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($_lightbox_w, $_lightbox_h); ?>" class = "a-lighbox" rel="lightbox[rotation]"></a>
	<!--++++++++++++-->
	<?php if($_zoom_type == 'regular' ) { ?>
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(1000,1330); ?>" class = "cloud-zoom" id="zoom1" style="position: relative; display: block;" rel="adjustX:10, adjustY:-2, zoomWidth:<?php echo $_zoom_w; ?>, zoomHeight:<?php echo $_zoom_h; ?>, showTitle:false">
	<?php } else { ?>
	<a href="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(1000,1330); ?>" class = "cloud-zoom" id="zoom1" style="position: relative; display: block;" rel="position:'inside', adjustX: 0, adjustY: 0, tint:'#ffffff', tintOpacity:0.1, smoothMove:3, showTitle:false">
	<?php } ?>
	
		<?php echo $_helper->productAttribute($_product, $_img, 'image'); ?>
	</a>
</p>
	
	<div class="more-views thumbnail-container horizontal visible-tablet">
				<h2><?php echo $this->__('More Views') ?></h2>
				<div class="flexslider carousel">
					<ul class="slides">
					<?php foreach ($this->getGalleryImages() as $_image): ?>
						<li class="thumbnail-item">
							<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(1000,1330); ?>" class="cloud-zoom-gallery" title="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>"
												rel="useZoom: 'zoom1', smallImage: '<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(500,670); ?>'">
							<img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize($_thumbnail_w, $_thumbnail_h); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
						</li>
					<?php endforeach; ?>
					</ul>
				</div>
				<?php //thumbnail for lighbox ?>
					<ul class="mt-thumb-light" style="display:none;">
						<?php foreach ($this->getGalleryImages() as $_image): ?>
							<li>
								<a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize($_lightbox_w, $_lightbox_h); ?>" rel="lightbox[rotation]" title="<?php echo $_product->getName();?>"></a>
							</li>
						<?php endforeach; ?>                                                                
					</ul>
				<?php //--##########-- ?>
				<script type="text/javascript">
					//<![CDATA[
						$jq('.thumbnail-container .flexslider').flexslider({
							<?php if( !$_auto ) { ?>
							slideshow: false,
							<?php } ?>
							itemWidth: <?php echo $_thumbnail_w ?>,
							itemMargin: 5,
							minItems: 2,
							maxItems: 4,
							<?php if (count($this->getGalleryImages()) < 5 ) { ?>
							directionNav: false,
							<?php } ?>
							controlNav: false,
							slideshowSpeed: 3000,
							animationSpeed: 500,
							animation: "slide"
						});		
					//]]>
				</script>
			</div>

	
		<div class="product-social" style="border-top:1px solid #d6d6d6;padding-top:10px;margin:10px 20px;text-align:center;">
				<?php if (Mage::getStoreConfig('themeoptions/themeoptions_config/social_buttons')): ?>
		        	<!-- AddThis Button BEGIN -->
					<div class="addthis_toolbox addthis_default_style addthis_16x16_style">
					<a class="addthis_button_facebook"></a>
					<a class="addthis_button_twitter"></a>
					<a class="addthis_button_pinterest_share"></a>
					<a class="addthis_button_google_plusone_share"></a>
					<a class="addthis_button_compact"></a><a class="addthis_counter addthis_bubble_style"></a>
					</div>
					<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=xa-52917fd70fb674a5"></script>
					<!-- AddThis Button END -->
				<?php endif ?>
		 </div>
	

</div>
</div>