<?php if (isset($useGetAddresses)): ?>
    <li>
        <div id="klarna_input">
            <div class="Klarna_pnoInputField">
                <label><?php echo $pno_label ?></label>
                <br/>
                <input
                    id="<?php echo $code; ?>_pno"
                    type="text"
                    name="<?php echo $pno_name; ?>"
                    class="klarna-validate-text input-text Klarna_pnoInputField"
                    value="<?php echo $pno; ?>"
                />
            </div>
        </div>
        <div class="klarna_box_bottom_address">
                <div class="klarna_box_bottom_address_title">
                    <?php echo $delivery_address; ?>
                </div>
            <div class="klarna_box_bottom_address_content">
            </div>

            <div class="klarna_box_bottom_address_title">
                <?php echo $goods_delivered_here; ?>
            </div>
        </div>
    </li>
<?php elseif (isset($showPno)): ?>
    <li>
        <label class="required" for="id_klarna_personalnumber">
            <?php echo $pno_label; ?>
        </label>
        <div class="input-box" style="width: 100%">
            <input
                type="text"
                name="<?php echo $pno_name; ?>]"
                id="<?php echo $code; ?>_pno"
                class="input-text klarna-validate-text"
                value="<?php echo $pno; ?>"
            />
        </div>
    </li>
<?php endif; ?>
