<?php
$fbfanbox = $this->getFbfanbox();
$storeCode = Mage::app()->getStore()->getCode();

if($fbfanbox['enable'])
{
	?>
	<div id="fb-root"></div>
	<?php if(strtolower($storeCode) == "nb"){?>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/nb_NO/sdk.js#xfbml=1&version=v2.3";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		</script>	
	<?php  } else { ?>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
		</script>
	<?php } ?>

	<div class="fb-page" data-href="<?php echo $fbfanbox['fb_page_url'];?>" data-width="<?php echo $fbfanbox['box_width'];?>" data-height="<?php echo $fbfanbox['box_height']; ?>" data-hide-cover="true" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="<?php echo $fbfanbox['fb_page_url'];?>"><a href="<?php echo $fbfanbox['fb_page_url'];?>">Vaktrommet as</a></blockquote></div></div>
	<?php 
}
?>
