<h2>Afterpay Faktura</h2>
<p>Vi tilbyr Afterpay Faktura i samarbeid med arvato Finance AS. Betalingsfrist er <?php echo $this->getInvoiceDueDays(); ?> dager. Hvis du velger å
betale med Afterpay Faktura, vil det i tillegg påløpe et fakturagebyr på <?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?> <?php echo $this->getInvoiceFee(); ?>. For å betale med faktura må du
ha fylt 18 år, være folkeregistrert i Norge samt bli godkjent i kredittvurderingen som gjennomføres ved
kjøpet.</p>
<p>
Ved forsinket betaling vil det bli sendt
betalingspåminnelse og/eller inkassovarsel, og lovbestemte gebyrer vil påløpe. Dersom betaling fortsatt
uteblir, vil fakturaen bli sendt til inkasso og ytterligere omkostninger vil påløpe. Ved forsinket betaling
beregnes lovbestemt forsinkelsesrente.
</p>
<p>
Ved å velge Afterpay Faktura får du
<ul>
<li>Trygghet til å handle uten å oppgi din kredittkortinformasjon</li>
<li>Mulighet til å handle gjennom å bare oppgi ditt personnummer</li>
<li>Mulighet til å se varen før du betaler</li>
<li>Handle enkelt, trygt og raskt på nettet</li>
</ul>
</p>
<p>
<strong><a href="https://www.arvato.com/content/dam/arvato/documents/norway-ecomm-terms-and-conditions/Vilkår for AfterPay Faktura.pdf">Les mer om Afterpay Faktura</a></strong>
