<h2>PayByBill Faktura</h2>
<p>Vi tilbyder PayByBill Faktura i samarbejde med arvato Finance A/S. Betalingsfrist er <?php echo $this->getInvoiceDueDays(); ?> dage. Hvis du vælger at betale med
PayByBill Faktura, vil du blive opkrævet et fakturagebyr på <?php echo Mage::app()->getStore()->getCurrencyCode(); ?> <?php echo $this->getInvoiceFee(); ?>,-. For at kunne betale med faktura skal du være fyldt 18 år, have
folkeregisteradresse i Danmark samt blive godkendt i kreditvurderingen, som sker ved købet.</p>
<p>Ved forsinket betaling vil der blive sendt en betalingspåmindelse og/eller inkassovarsel, og lovbestemte gebyrer vil påløbe. Hvis betalingen
fortsat udebliver, vil fakturaen blive sendt til inkasso og yderligere omkostninger vil påløbe. Ved forsinket betaling beregnes forsinkelsesrenter
i henhold til lovgivningen.</p>
 
<p>Ved at vælge PayByBill Faktura får du:
<ul>
<li>Tryghed ved at handle uden at skulle oplyse kreditkortoplysninger</li>
<li>Mulighed for at handle ved brug af fødselsdato og folkeregisteradresse</li>
<li>Mulighed for at se varen før du betaler</li>
<li>Mulighed for enkel, tryg og hurtig handel på Nettet.</li>
</ul>
</p>
<p><strong><a href="http://finance-arvato-stage.uscreen.net/fileadmin/user_upload/Norway/Kontovilkaar_standard.pdf">Læs mere om PayByBill Faktura</a></strong></p>
