<h2>PayByBill Rechnung</h2>
<p>Wir bieten PayByBill Rechnung in einer Partnerschaft mit arvato Finance an. Das Zahlungsziel beträgt <?php echo $this->getInvoiceDueDays(); ?> Tage. Wenn Sie PayByBill Rechnung als Zahlart auswählen, wird Ihnen eine Rechnungsgebühr von <?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?> <?php echo $this->getInvoiceFee(); ?> berechnet.
Berechtigt für den Rechnungskauf mit PayByBill sind Sie, wenn Sie mindestens 18 Jahre alt sind, in Deutschland wohnhaft gemeldet sind und eine positive Bonitätsprüfung erhalten haben, welche durch Ihren Kauf beeinflusst wird.</p>
<p>Im Falle eines Zahlungsverzuges werden Sie eine Zahlungserinnerung und / oder Mahnung erhalten, die mit weiteren Gebühren verbunden sein können.
Im weiteren Verlauf wird die Rechnung im Falle der Nichtzahlung an ein Inkassounternehmen überstellt wodurch weitere Kosten verursacht werden. Im Falle des Zahlungsverzuges werden weiterhin Verzugszinsen berechnet.</p>

<p>
Durch die Wahl von PayByBill als Zahlart erhalten Sie,
<ul>
        <li>die Sicherheit eines Einkaufs ohne Ihre Kreditkarteninformationen offen legen zu müssen</li>
        <li>die Möglichkeit nur mit der Eingabe des Geburtsdatums und der Meldeadresse einzukaufen</li>
        <li>die Möglichkeit die Ware zu sehen bevor Sie diese bezahlen</li>
        <li>die Möglichkeit eines einfachen, sicheren und schnellen Einkaufs im Internet</li>
</ul>
</p>
