<h2>PayByBill – Faktura</h2>
<p>Vi erbjuder PayByBill i samarbete med arvato Finance AB. Betalningsvillkor är <?php echo $this->getInvoiceDueDays(); ?> dagar och vid fakturaköp tillkommer en avgift om <?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?> <?php echo $this->getInvoiceFee(); ?>. För att kunna beställa mot faktura måste Du ha fyllt 18 år och vara folkbokförd i Sverige samt godkännas i den kreditprövning som genomförs vid köpet.</p>
<p>Fakturan kommer att sändas separat. Vid försenad betalning skickar vi en betalningspåminnelse varvid lagstadgad påminnelseavgift om för närvarande 60 kr tillkommer. Vi debiterar även dröjsmålsränta med <?php echo $this->getInvoiceLateFee(); ?> % från fakturans förfallodag. Vid utebliven betalning lämnas ärendet till inkasso varvid lagstadgad inkassoavgift om för närvarande 180 kr tillkommer.</p>
<p>Arvato kommer att behandla beställarens personuppgifter i enlighet med personuppgiftslagen. Uppgifter kommer att insamlas och behandlas i syfte att slutföra den aktuella beställningen, identifiera beställaren, genomföra kreditkontroll samt för statistiska syften. Genom att välja betalning mot faktura, PayByBill Konto eller PayByBill delbetalning ger beställaren arvato rätt att via externa och interna databaser genomföra identifikations- och kreditkontroll.</p>
<p>När du väljer PayByBill Faktura får du</p>
<ul>
<li>Trygghet att handla utan att ange dina kreditkortsuppgifter</li>
<li>Möjligheten att handla genom att bara ange ditt personnummer</li>
<li>Möjligheten att se varan innan du betalar</li>
<li>Handla enkelt, tryggt och snabbt på nätet</li>
</ul>
<p><strong><a href="http://finance-arvato-stage.uscreen.net/fileadmin/user_upload/Sweden/Kontovillkor/Kontovillkor.pdf">Läs mer om PayByBill Faktura</a></strong></p>
