<h2>Afterpay Invoice</h2>
<p>We offer Afterpay Invoice in partnership with arvato Finance. Payment deadline is <?php echo $this->getInvoiceDueDays(); ?> days. If you choose to pay by
Afterpay Invoice you will be charged an invoice fee of <?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?> <?php echo $this->getInvoiceFee(); ?>. To be eligible to pay by invoice  you must be 18 years of age,
have your registered address in <country> and be approved in the credit rating process, which is affected by the purchase.</p>
<p>If your payment is late you will be sent a payment reminder and / or collection notice and legal fees will be incurred . If the payment
still fails to appear, the invoice will be sent to a collection agency and additional costs will be incurred. In case of late payment, delay interest
under the law.</p>
<p> 
By choosing Afterpay Invoice you get:
<ul>
        <li>Security of shopping without having to disclose credit card information</li>
        <li>Ability to act using date of birth and registered address</li>
        <li>Ability to see the goods before you pay</li>
        <li>A simple, secure and fast trade on the Internet</li>
</p> 
<p>
<strong><a href="http://www.afterpay.no/en/secure-way-pay">Read more about Afterpay Invoice</a></strong>
</p>
