<h2>PayByBill-lasku</h2>

<p>Me tarjoamme PayByBill-laskun yhteistyössä arvato financen kanssa. Maksuaikaa on <?php echo $this->getInvoiceDueDays(); ?> päivää. Jos päätät maksaa PayByBill-laskulla, niin sinulta veloitetaan laskutuspalkkiona <?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?> <?php echo $this->getInvoiceFee(); ?>. Voidaksesi maksaa laskulla sinun täytyy olla 18-vuotias ja sinulla on oltava rekisteröity osoite Suomessa. Sen lisäksi ostoksesi pitää tulla hyväksytyksi luottoarvioprosessissa.</p>

<p>Jos maksusi on myöhässä sinulle lähetetään maksuhuomautus, johon voi sisältyä lakiin perustuvia kustannuksia. Jos maksu edelleenkin puuttuu, niin lasku lähetetään perintätoimistolle ja tästä aiheutuu lisäkustannuksia. Myöhästyneestä maksusta peritään myös korkolain mukaista viivästyskorkoa.</p>

<p>
Valitsemalla PayByBill-laskun saat:
<ul>
        <li>Turvallisen ostotavan, jossa sinun ei tarvitse luovuttaa luottokorttisi tietoja</li>
        <li>Mahdollisuuden hoitaa ostoksesi vain käyttämällä henkilötunnustasi ja rekisteröityä osoitettasi</li>
        <li>Mahdollisuuden tarkistaa ostamasi tuotteet ennen kuin maksat niistä</li>
        <li>Helpon, turvallisen ja nopean tavan tehdä kauppaa Internetissä</li>
</ul>
</p>

<p><strong><a href="http://finance.arvato.com/fileadmin/user_upload/Finland/terms_conditions/PBB_-_arvato_Finance_-_Luottoehdot_-_20032014.pdf">Lue lisää PayByBill-laskusta</a></strong></p>
