<h2>PayByBill Rammekreditt</h2>
<p>Vi tilbyr PayByBill Rammekreditt i samarbeid med arvato Finance AS. Ved PayByBill Rammekreditt har du
som kunde mulighet til å dele opp betalingen. Du velger selv om du ønsker å betale et angitt «minstebeløp
å betale» på tilsendt månedsfaktura eller betale mer om du heller ønsker det. Du kan når som helst, uten
ekstra kostnad, velge å avslutte din PayByBill Rammekreditt ved å betale inn hele det resterende
kredittbeløpet.</p>
<p>
Det er enkelt å få PayByBill Rammekreditt. Følgende 3 steg skal til for å åpne din personlige rammekreditt;<br />
1. Velg PayByBill Rammekreditt eller PayByBill Faktura som betalingsmåte i nettbutikken<br />
2. Betal «Aktiveringsbeløpet» som angitt på mottatt faktura<br />
3. Signer og returner kredittavtalen som blir tilsendt deg<br />
</p>
<p>
Priseksempel; Kr. 5.000, o/12 mnd., eff. Rente 39,33 %, totalt kr. 5.939.
</p>
<p>
<strong><a href="http://www.gothiagroup.com/fileadmin/Norway/pdf/PBB_rammkreditt_standard.pdf">Les mer om PayByBill Rammekreditt</a></strong>
</p>
