<?php if (isset($consent)): ?>
    <li>
        <div class='klarna_box_bottom_input_combo' style='width: 100%'>
            <input
                type='checkbox'
                name='<?php echo $consent_name;?>'
                id='box_<?php echo $code; ?>_consent'
                style='float: left; margin-right: 3px'
                class='klarna-validate-checkbox'
                value='consent'
            />
            <?php echo $consent_div; ?>
        </div>
    </li>
<?php endif; ?>
