<?php if (isset($dob)): ?>
    <li>
        <label><?php echo $dobLabel; ?></label>
        <div class="input-box">
            <select
                name="<?php echo $dob_day_name;?>"
                class="klarna-validate-select"
                style="width: 60px !important; margin-right: 5px;"
            >
                <option value="00" disabled="disabled"
                    <?php if ($day_disabled): ?>
                        selected="selected"
                    <?php endif; ?>
                >
                    <?php echo $dayLabel; ?>
                </option>

                <?php for ($x=1; $x <= 31; $x++): ?>
                    <option
                        value="<?php echo sprintf("%02d", $x); ?>"
                        <?php if ($dob_day == $x): ?>
                            selected="selected"
                        <?php endif; ?>
                    >
                        <?php echo sprintf("%02d", $x); ?>
                    </option>
                <?php endfor; ?>
            </select>

            <select
                name="<?php echo $dob_month_name;?>"
                class="klarna-validate-select"
                style="width: 60px !important; margin-right: 5px;"
            >
                <option value="00" disabled="disabled"
                    <?php if ($month_disabled): ?>
                        selected="selected"
                    <?php endif; ?>
                >
                    <?php echo $monthLabel; ?>
                </option>

                <?php for ($x=1; $x <= 12; $x++): ?>
                    <option
                        value="<?php echo sprintf("%02d", $x); ?>"
                        <?php if ($dob_month == $x): ?>
                            selected="selected"
                        <?php endif; ?>
                    >
                        <?php echo sprintf("%02d", $x); ?>
                    </option>
                <?php endfor; ?>
            </select>

            <select
                name="<?php echo $dob_year_name;?>"
                class="klarna-validate-select"
                style="width: 65px !important;"
            >
                <option
                    value="00"
                    disabled="disabled"
                    <?php if ($year_disabled): ?>
                    selected="selected"
                    <?php endif; ?>
                >
                    <?php echo $yearLabel; ?>
                </option>

                <?php for ($x=date('Y'); $x > (date('Y')-100); $x--): ?>
                    <option
                        value="<?php echo $x; ?>"
                        <?php if ($dob_year == $x): ?>
                             selected="selected"
                         <?php endif; ?>
                     >
                        <?php echo $x; ?>
                    </option>
                <?php endfor; ?>
            </select>
        </div>
    </li>
<?php endif; ?>
