<?php if (isset($pclasses)): ?>
    <li>
        <ul id="<?php echo $code; ?>_pclasses" style="width: 200px;" class="paymentPlan">
            <?php foreach ($pclasses as $pclass): ?>
                <li>
                    <label for="pclass_<?php echo $pclass['id']?>">
                        <input
                            id="pclass_<?php echo $pclass['id']?>"
                            type="radio"
                            name="<?php echo $pclasses_name; ?>"
                            value='<?php echo $pclass['id']; ?>'
                            <?php if ($pclass['default'] === true) :?>
                                checked="checked"
                            <?php endif; ?>
                        />
                        <?php
                            echo $pclass['description'];
                            if ($pclass['cost']) {
                                echo " - {$pclass['cost']} /{$monthLabel}";
                            }
                        ?>
                    </label>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
<?php endif; ?>
