<div class="entry-edit">
    <div class="entry-edit-head"><h4 class="icon-head head-shipping-method">Information from Klarna</h4></div>
        <fieldset>
            Currently it is not possible to edit a reservation from here. If you wish to edit a reservation you have to cancel this order and visit Klarna Online to create a new order there. Please visit <a href="<?php echo $target;?>">Klarna Online</a> for more information.
        </fieldset>
    </div>
<div style="clear: both;"></div>
