<input type="hidden" id="<?php echo $field; ?>" name="<?php echo $field; ?>" value="" />
<button
    type="button"
    class="scalable save"
    onclick="$('<?php echo $field; ?>').setValue('view');configForm.submit();">
    <span>View PClasses</span>
</button>
<button
    type="button"
    class="scalable save"
    onclick="$('<?php echo $field; ?>').setValue('update');configForm.submit();">
    <span>Update PClasses</span>
</button>
