<?php
$_code=$this->getMethodCode();
$_lang=$this->getLanguageCode();

?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="<? echo ($this->getAjaxCall() ? '' : 'display:none;'); ?>">
    <li>
        <label for="<?php echo $_code ?>_dd_bankid" class="required validate-select"><em>*</em><?php echo $this->__('Bank ID') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_dd_bankid" class="required-entry input-text" name="payment[dd_bankid]" title="<?php echo $this->__('Bank ID') ?>" class="input-text" value="<?php echo $this->getBankId(); ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_dd_bankaccount" class="required"><em>*</em><?php echo $this->__('Bank Account') ?></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_dd_bankaccount" class="required-entry input-text" name="payment[dd_bankaccount]" title="<?php echo $this->__('Bank Account') ?>" class="input-text" value="<?php echo $this->getBankAccount(); ?>" />
        </div>
    </li>
</ul>
