<?php $product = Mage::registry('product');?>
<?php if($product->getImage() != 'no_selection') : ?>
<div>
	<button class="scissorselpopup" onclick="openPopUp()"><?php echo $this->__('Select Scissors Area');?></button>
	<div id="scissorselpopup">
		<div class="closeScissorSel"></div>
        
	   	<span class="ecs_tooltip">Press Esc to close <span class="arrow"></span></span>
        
		<div id="popup_content_scissor_sel">
		

		 <h5 class="boxtite1"><?php echo $this->__('You can Select the Area either by Drag & Drop or by changing the Co-ordinates Input ');?></h5>
		 <h5 class="boxtite2"><?php echo $this->__('Note : Please save the product once you finish editing ');?></h5>

		<input type="hidden" name="scissorselx1Val" id="scissorselx1Val" value="<?php echo $product->getPrbImgSciselX1();?>" ></input>
		<input type="hidden" name="scissorselx2Val" id="scissorselx2Val" value="<?php echo $product->getPrbImgSciselX2();?>"></input>
		<input type="hidden" name="scissorsely1Val" id="scissorsely1Val" value="<?php echo $product->getPrbImgSciselY1();?>"></input>
		<input type="hidden" name="scissorsely2Val" id="scissorsely2Val" value="<?php echo $product->getPrbImgSciselY2();?>"></input>
        <div class="boximg">
            <?php list($Imgwidth, $Imgheight)  = getimagesize(Mage::helper('catalog/image')->init($product, 'image'));

				if($Imgwidth > 395 && $Imgheight > 770)
				{
			?>

				<img id="imgScissorSelSel" src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(395,770); ?>"/>
			<?php } 
				else if($Imgwidth > 395 && $Imgheight < 770)
				{
				?>
					<img id="imgScissorSelSel" src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(395,$Imgheight); ?>"  > 
				<?php
				}

				else if($Imgwidth < 395 && $Imgheight > 770)
				{
				?>
					<img id="imgScissorSelSel" src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize($Imgwidth,770); ?>"  > 
				<?php
				}

				else 
				{
				?>
					<img id="imgScissorSelSel" src="<?php echo Mage::helper('catalog/image')->init($product, 'image'); ?>"  > 
				<?php
				}
			?>
            
            <?php /*list($Imgwidth, $Imgheight)  = getimagesize(Mage::helper('catalog/image')->init($product, 'image'));

				if($Imgwidth > 395 || $Imgheight > 770)	
				{
			?>

				<img id="imgScissorSelSel" src="<?php echo Mage::helper('catalog/image')->init($product, 'image')->resize(395,770); ?>"/>
			<?php } 
				else 
				{
				?>
					<img id="imgScissorSelSel" src="<?php echo Mage::helper('catalog/image')->init($product, 'image'); ?>"  > 
				<?php
				}
			*/?>
</div>

		<div style class="poprightbox" ="float:right;">	
			<div style="float:left";>
			<label for="x1">X1:</label>
			<input type="text" name="showscissorselx1" id="showscissorselx1" value="<?php echo $product->getPrbImgSciselX1() ? $product->getPrbImgSciselX1() : '' ;?>" style="width:50px;" ></input></div>
			<div style="clear:both"></div>

			<div style="float:left";>
			<label for="x1">X2:</label>
			<input type="text" name="showscissorsely1" id="showscissorsely1" value="<?php echo ($product->getPrbImgSciselY1()) ? $product->getPrbImgSciselY1() :'';?>" style="width:50px;" ></input></div>
			<div style="clear:both"></div>

			<div style="float:left";>
			<label for="x1">Y1:</label>		
			<input type="text" name="showscissorselx2" id="showscissorselx2" value="<?php echo ($product->getPrbImgSciselX2()) ? $product->getPrbImgSciselX2() : '';?>" style="width:50px;" ></input></div>
			<div style="clear:both"></div>

			<div style="float:left";>
			<label for="x1">Y2:</label>
			<input type="text" name="showscissorsely2" id="showscissorsely2" value="<?php echo ($product->getPrbImgSciselY2()) ? $product->getPrbImgSciselY2() : '';?>" style="width:50px;" ></input></div>
			<div style="clear:both"></div>
		</div>	

		</div>
	</div>
		<div class="loader"></div>
	   	<div id="backgroundScissorSelPopup"></div>
</div>

<script type="text/javascript">
$j = jQuery.noConflict();

	function openPopUp()
	{
		return false;
	}

</script>
<?php endif; ?>