<?php

/**
 * Dibs A/S
 * Dibs Payment Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Payments & Gateways Extensions
 * @package    Dibspw_DibspwModule
 * @author     Dibs A/S
 * @copyright  Copyright (c) 2010 Dibs A/S. (http://www.dibs.dk/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$paymate = Mage::getModel('dibspw/Dibspw');
$_code=$this->getMethodCode();
$sHTML = '<fieldset class="form-list">
          <ul id="payment_form_'.$_code. '" style="display:none">
          <li>' . $this->__('DIBSPW_LABEL_1');
$aLogoArray = explode(',', $paymate->getConfigData('dibspwlogos'));

$sTrusted = '';
$sCards = '';
$iCards = 1;
$iTrusted = 1;
foreach($aLogoArray as $item) {
    $mSecured = (boolean)preg_match("/^(DIBS|PCI|.*_SECURE.*)$/s", $item);
    if($mSecured === TRUE){
        $sTrusted .= $paymate->cms_get_imgHtml($item) . "&nbsp;&nbsp;";
        if($iTrusted%12 == 0) $sTrusted .= "<br />";
        $iTrusted++;
    }
    else {
        $sCards .= $paymate->cms_get_imgHtml($item) . "&nbsp;&nbsp;";
        if($iCards%12 == 0) $sCards .= "<br />";
        $iCards++;
    }
}

if(!empty($sTrusted)) $sHTML .= '<br /><br />' . $sTrusted;
if(!empty($sCards)) $sHTML .= '<br /><br />' . $this->__('DIBSPW_LABEL_2') . '<br />' . $sCards;

$sHTML .= '</li></ul></fieldset>';

echo $sHTML;
?>