<?php

/**
 * Dibs A/S
 * Dibs Payment Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Payments & Gateways Extensions
 * @package    Dibspw_DibspwModule
 * @author     Dibs A/S
 * @copyright  Copyright (c) 2010 Dibs A/S. (http://www.dibs.dk/)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$oPaymate = Mage::getModel('dibspw/Dibspw');
$aDibsparmeter = $oPaymate->getCheckoutFormFields();
?>
<h2><?php echo $this->__('DIBSPW_LABEL_24') ?></h2>
<form method="post" id="dibspw-payment" action ="<?php echo dibs_pw_api::api_dibs_get_formAction(); ?>">
    <div>
        <?php foreach($aDibsparmeter as $sField => $sVal) {?> 
            <input type="hidden" name="<?php echo $sField; ?>" value="<?php echo htmlentities($sVal, ENT_QUOTES, 'UTF-8'); ?>" /> 
        <?php } ?>
    </div>
</form>

<script type="text/javascript">
    setTimeout("document.getElementById('dibspw-payment').submit();", 1000);
</script>