<!--
/**
 * Klarna
 * JavaScript includes for OneStepCheckout
 */
-->
<?php
    include dirname(__FILE__) . '/scripts.phtml';
?>

<script type="text/javascript">
    (function (Klarna) {
        "use strict";

        var KE = Klarna.use('Event');

        function updateSelected() {
            var url = window.location.href + "ajax/save_billing/";
            get_separate_save_methods_function(url, false).call();
        }

        KE.bind('ready', updateSelected);
    })(Klarna);
</script>
